title: "Bo Chen"
description: "Good Luck, Have Fun"
about: "So if you want to go fast, if you want to get done quickly, if you want your code to be easy to write, make it easy to read."
quoteAuthor: "― Robert C. Martin, Clean Code: A Handbook of Agile Software Craftsmanship"
location: "Atlanta, Georgia"
email: bochentheone@gmail.com
baseurl: ""
url: "http://bochentheone.com" # replace by your site's url
twitter_username: bochen_bo
github_username:  whilelooper
telegram: bochentheone

# google analytics tracking code, please change the value
g_analytics: "UA-64802678-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4
  
# exclude files
exclude:
  - LICENSE
  - README.md
